server:
  port: 8081

spring:
  application:
    name: order-service
  
  # Configuraci贸n de PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/ordersdb
    username: orderuser
    password: orderpass
    driver-class-name: org.postgresql.Driver
  
  # Configuraci贸n de JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Configuraci贸n de Kafka Producer
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderEvent:com.example.orderservice.event.OrderEvent
    
# Configuraci贸n del topic
kafka:
  topic:
    name: order-events

# Logging
logging:
  level:
    com.example.orderservice: DEBUG
    org.springframework.kafka: INFO